#if !canImport(ObjectiveC)
import XCTest

extension TextLayoutTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextLayoutTests = [
        ("testBoundsForCharacters", testBoundsForCharacters),
        ("testHitTestPoint", testHitTestPoint),
        ("testHitTestPointMultiline", testHitTestPointMultiline),
        ("testHitTestPointOutsideBoxBelow", testHitTestPointOutsideBoxBelow),
        ("testHitTestPointOutsideBoxRight", testHitTestPointOutsideBoxRight),
        ("testHitTestPointTrailing", testHitTestPointTrailing),
        ("testLocationOfCharacter", testLocationOfCharacter),
        ("testLocationOfCharacterOffBounds", testLocationOfCharacterOffBounds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TextLayoutTests.__allTests__TextLayoutTests),
    ]
}
#endif
